# what are the anatomical body parts participating in the movement?

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX khmo: <http://w3id.org/khmo#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

SELECT DISTINCT ?ana WHERE
{
	{
		?stance_a obo:BFO_0000063 ?stance_b .
		?ana_a obo:RO_0002327 ?stance_a .
		?ana_a rdfs:label ?ana.
	}
	UNION
	{
		?stance_a obo:BFO_0000063 ?stance_b .
		?ana_b obo:RO_0002327 ?stance_b .
		?ana_b rdfs:label ?ana.
	}

}
